import _beercss from "beercss";
import _materialDynamicColors from "material-dynamic-colors";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "beercss/dist/cdn/beer.min.css";

import "@/app/globals.css";
import Header from "@/app/components/Header";
import ThemeProvider from "@/providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const GlobalLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} dark`}>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};
